# Generated by Django 5.0.6 on 2024-06-01 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_movie_description_alter_movie_director_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Article',
        ),
    ]
